name: Build - Windows

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/**'
    branches:
      - main

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 2
  MAKEFLAGS: '-j 2'
  VCPKG_ROOT: ${{ github.workspace }}/vcpkg

jobs:
  build-windows:
    runs-on: windows-2022
    name: Windows Build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup CCache
        uses: hendrikmuhs/ccache-action@v1
        with:
          max-size: "1G"

      - name: Install dependencies
        shell: pwsh
        run: |
          git clone https://github.com/microsoft/vcpkg.git $env:VCPKG_ROOT
          cd $env:VCPKG_ROOT
          .\bootstrap-vcpkg.bat
          cd $env:GITHUB_WORKSPACE

      - name: Install CMake y Ninja
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: 3.27.9
          ninjaVersion: latest

      - name: Configure with CMake
        run: |
          cmake -S . -B build-windows-release `
            -DCMAKE_BUILD_TYPE=RelWithDebInfo `
            -DCMAKE_TOOLCHAIN_FILE=${env:VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake `
            -DVCPKG_TARGET_TRIPLET=x64-windows-static `
            -G "Ninja"

      - name: Build project
        run: cmake --build build-windows-release

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: otclient-windows.exe
          path: build-windows-release/otclient.exe
