---
name: Build - Windows

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - 'src/**'
  push:
    paths:
      - 'src/**'
    branches:
      - main

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 2
  MAKEFLAGS: '-j 2'

jobs:
  cancel-runs:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  build:
    if: ${{ github.event_name == 'push' || !github.event.pull_request.draft }}
    name: ${{ matrix.os }}-${{ matrix.buildtype }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-2022]
        buildtype: [windows-release]
        include:
          - os: windows-2022
            triplet: x64-windows
            packages: sccache

    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set working directory
        run: echo "Working in ${{ github.workspace }}"

      - name: Setup CCache
        uses: hendrikmuhs/ccache-action@v1
        with:
          max-size: "1G"
          variant: "sccache"
          key: ccache-${{ matrix.os }}-${{ matrix.buildtype }}
          restore-keys: |
            ccache-${{ matrix.os }}

      - name: Remove Windows pre-installed MySQL
        if: contains(matrix.os, 'windows')
        run: Remove-Item -Recurse -Force "C:\mysql*"

      - name: Parse vcpkg.json and export VCPKG commit
        id: vcpkg-step
        shell: pwsh
        run: |
          $json = Get-Content "${{ github.workspace }}/vcpkg.json" -Raw | ConvertFrom-Json
          $vcpkgCommitId = $json.'builtin-baseline'
          echo "VCPKG_GIT_COMMIT_ID=$vcpkgCommitId" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Install vcpkg from builtin-baseline
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitURL: "https://github.com/microsoft/vcpkg.git"
          vcpkgGitCommitId: ${{ env.VCPKG_GIT_COMMIT_ID }}
          workingDirectory: ${{ github.workspace }}

      - name: Get latest CMake and Ninja
        uses: lukka/get-cmake@latest

      - name: Run CMake and build
        uses: lukka/run-cmake@v10
        with:
          configurePreset: ${{ matrix.buildtype }}
          buildPreset: ${{ matrix.buildtype }}
          workingDirectory: ${{ github.workspace }}

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: otclient-${{ matrix.buildtype }}-${{ github.sha }}
          path: ${{ github.workspace }}/otclient.exe
